### ISSUE TITLE
NEA dropped their FISMA reports page

### ISSUE THREAD

**Issue by konklone** [unitedstates/inspectors-general#186]
[The old FISMA page](http://arts.gov/oig/reports/fisma) is gone. Here's a snapshot from the Wayback Machine:

http://web.archive.org/web/20140713230749/http://arts.gov/oig/reports/fisma

It's one report a year from 2004-2013. We have them downloaded in our old cache. I've emailed the NEA webmaster to see what's up.

**Comment by spulec** [comment]
Just want to note for anyone else that wants copies of these reports that the historical ones are still available via

`http://arts.gov/sites/default/files/nea-fisma-<year>.pdf`
`http://arts.gov/sites/default/files/nea-<year>-fisma-summary.pdf`

at least for now.

**Comment by spulec** [comment]
I emailed them and they responded that the reports are now available under the [Internal Reviews](http://arts.gov/inspector-general/reports/internal-reviews). It looks like we will just need to modify the scraper a bit.
