### ISSUE TITLE
NSA Reports to the President's Intelligence Oversight Board

### ISSUE THREAD

**Issue by handlers** [unitedstates/inspectors-general#192]
The NSA has [released over a decade's worth](http://mobile.bloomberg.com/news/2014-12-24/spy-agency-to-release-reports-documenting-surveillance-errors.html) of oversight documents pertaining to the [President's Intelligence Oversight Board](http://www.whitehouse.gov/administration/eop/piab) (I'm not sure if the release was legally _required_ after an ACLU FOIA request or if it was a voluntary concession after an ACLU FOIA request). They are up [here](https://www.nsa.gov/public_info/declass/IntelligenceOversightBoard.shtml). 

 While not _necessarily_ the sole work of the IG — a spot check shows they're often a joint production of the NSA General Counsel and the NSA IG — they might be worth adding to this collection.

Before we do that, I think it's worth thinking about a couple of questions:

1. If we decided to put them in inspectors-general, would it be correct to note the `inspector_general` as `nsa`, even though the NSA General Counsel was sometimes involved?
2. Do these documents actually belong in the inspectors-general repository? They certainly _involve_ an inspector general but are not the sole production of a single inspector. Would it be more appropriate to put them in something like `unitedstates/oversight`, along with things like the [recent Senate Select Committee on Intelligence report on CIA interrogation](https://en.wikipedia.org/wiki/Senate_Intelligence_Committee_report_on_CIA_torture)? 
3. Do we have/need infrastructure for dealing with ad-hoc document dumps like this? Given that this was provoked by a FOIA request (and required a classification review), it seems unlikely that the NSA is going to continue posting them as time goes by.

**Comment by konklone** [comment]
> 1. If we decided to put them in inspectors-general, would it be correct to note the inspector_general as `nsa`, even though the NSA General Counsel was sometimes involved?

If we were to put them here, then yes, I think `nsa` would be right.

> 2. Do these documents actually belong in the inspectors-general repository? They certainly _involve_ an inspector general but are not the sole production of a single inspector. Would it be more appropriate to put them in something like `unitedstates/oversight`, along with things like the [recent Senate Select Committee on Intelligence report on CIA interrogation](https://en.wikipedia.org/wiki/Senate_Intelligence_Committee_report_on_CIA_torture)? 

I love the idea of a place to put manually curated oversight reports generally, wherever they come from (GAO, IG, Congress, etc). Perhaps the repository could version the `.json` metadata for each report, while they reference an archive.org URL for the actual report PDF(s)? Maybe it could could also include some small tooling to help upload PDFs to the Internet Archive. An S3 bucket, e.g. `unitedstates.sunlightfoundation.com`, could also work.

> 3. Do we have/need infrastructure for dealing with ad-hoc document dumps like this? Given that this was provoked by a FOIA request (and required a classification review), it seems unlikely that the NSA is going to continue posting them as time goes by.

We're really missing out by not having a way of accepting and processing reports that come through FOIA. It should be easy for anyone who wants to integrate those reports into the main scraped collection to do so.

**Comment by spulec** [comment]
I have opened a PR to add these to the https://github.com/unitedstates/reports/ repo here: https://github.com/unitedstates/reports/pull/1

**Comment by spulec** [comment]
I'm closing since that PR was merged.
