### ISSUE TITLE
Wrong dates for some reports?

### ISSUE THREAD

**Issue by nickom** [unitedstates/inspectors-general#193]
Scout is showing a bunch of IG reports dated in the future:
https://scout.sunlightfoundation.com/search/documents/*?documents%5Bdocument_type%5D=ig_report

Any ideas what's going on?
![screen shot 2015-01-15 at 3 42 33 pm](https://cloud.githubusercontent.com/assets/3171982/5766140/24317c06-9ccd-11e4-8eb6-2eb0ce13cc6e.png)
![screen shot 2015-01-15 at 3 42 26 pm](https://cloud.githubusercontent.com/assets/3171982/5766144/26531698-9ccd-11e4-865e-0878d6ab0b31.png)
![screen shot 2015-01-15 at 3 42 17 pm](https://cloud.githubusercontent.com/assets/3171982/5766146/2f051b56-9ccd-11e4-96a2-a1ec1343d186.png)

**Comment by spulec** [comment]
It looks like this is a result of the code [here](https://github.com/unitedstates/inspectors-general/blob/master/inspectors/archives.py#L73-L76)

Basically, if we can't find when the report was published, we set it to November 1st of the year mentioned in the title. This is obviously suboptimal, but it wasn't clear that there was a better option. If you can find a better way to get a more accurate published date (in some of the later scrapers I think we checked pdf metadata), it would certainly be welcome.
