### ISSUE TITLE
Denali OIG has a new website

### ISSUE THREAD

**Issue by divergentdave** [unitedstates/inspectors-general#207]
I'm checking for scrapers that have silently broken due to website changes, (PR soon) and it looks like the Denali OIG has a brand new website, in part because they have a new Acting Inspector General. The first problem is that the site needs a new scraper written. The second problem is that all of the pre-2013 reports don't appear on the new site. Should we hang on to an old archive in unitedstates/reports per #204?

(ref. #161)

**Comment by konklone** [comment]
> Should we hang on to an old archive in unitedstates/reports per #204?

If we have to, yes, though that'd be an annoying outcome. The Denali reports are currently [backed up in the Internet Archive](https://archive.org/details/us-inspectors-general.bulk), so we're not in imminent danger of losing them.

I think the next two TODOs are:

- [ ] Write a new scraper.
- [ ] Contact the new Denali OIG and ask what their plans are for the old reports.

I'm happy to call the new OIG, their number is (206) 220-7970. They also have a [shiny new Twitter account](https://twitter.com/denalioig), and I've turned on push notifications for all tweets from them.

**Comment by divergentdave** [comment]
Upon closer inspection, there actually are pre-2013 reports on the website. I'm not sure what I was looking at.

Semiannual reports are all there, inspection reports are all there, and the entire financial/performance reports have been posted, rather than extracts of the IG-written sections. However, the 2007 financial/performance report isn't posted. ([IA link](https://web.archive.org/web/20140919214659/http://www.oig.denali.gov/Images/IG-PAR-2007.pdf)) None of the GAO decisions were posted, but we weren't scraping those anyway.

**Comment by konklone** [comment]
Closing as good enough.
