### ISSUE TITLE
[usps] [sba] Reports are falling through the cracks between pages

### ISSUE THREAD

**Issue by divergentdave** [unitedstates/inspectors-general#214]
As described in #213, the USPS document library uses an unstable sort algorithm. If more than one report with the same date span a pagination boundary, we may see one report on both pages while missing another report entirely. We could probably detect this and re-fetch the offending pages until we make up the difference.

**Comment by divergentdave** [comment]
The SBA scraper has the same problem

**Comment by konklone** [comment]
Really? I would not expect this to be a common issue.

The easiest way to solve both issues would seem to be to specify an explicit sort order.

**Comment by divergentdave** [comment]
I can certainly see how it could happen, writing `ORDER BY datetime DESC` or `ORDER BY year DESC, month DESC, date DESC` seems like the sensible thing to do. I have a plan for retrying pages when we miss rows, going to try it out on SBA first.

**Comment by divergentdave** [comment]
Closed by #223
