### ISSUE TITLE
Are there any web scrapers that need to be written?

### ISSUE THREAD

**Issue by jackiekazil** [unitedstates/inspectors-general#224]
Are there any web scrapers that need to be written for this repo?

@Sisiwei and I are [teaching a web scraping class](https://us.pycon.org/2015/schedule/presentation/318/) @ Pycon and we are looking for possible challenges for folks to dig into.

**Comment by konklone** [comment]
Our current scope is the 70+ federal IGs under the scope of the [Council of Inspectors General](https://www.ignet.gov/), that publish reports online in a scrape-able place. We also have the House of Representatives IG in there.

There are a few places we could happily expand to cover more areas of oversight, I think.

* The [Government Accountability Office](http://www.gao.gov), a legislative branch agency that performs oversight on the executive branch. They also are asked to review IGs themselves now and then. They [publish reports](http://www.gao.gov/browse/date/week), and have an [undocumented API](http://www.gao.gov/api/id/669198) which I once used to write a [Ruby scraper](https://github.com/sunlightlabs/congress/blob/master/tasks/gao_reports/gao_reports.rb) that sits inside the belly of a larger app that serves [a search engine](https://scout.sunlightfoundation.com/search/documents/*?documents[document_type]=gao_report). Re-implementing this in Python, and in a standalone project like this, will expand the reach of their work.

* The [House Oversight Committee](http://oversight.house.gov/report/), amidst all the politics, produces a lot of meaningful oversight reports. I don't know how to think of the [minority reports](http://democrats.oversight.house.gov/news/reports), but they exist too.

* The [Senate Committee on Homeland Security and Governmental Affairs](http://www.hsgac.senate.gov/) is the Senate's oversight committee. They [publish reports too](http://www.hsgac.senate.gov/library?c=113&type=reports), though that link is filtering it down to "Reports" in the 113th Congress (none in 114th yet). Also, [this page](http://www.hsgac.senate.gov/subcommittees/investigations/reports) links to a [PDF of investigation links](http://www.hsgac.senate.gov/download/?id=68ef4012-233f-40c7-a1da-c960bc82f581) by the investigations subcommittee.

* Also, GPO keeps a massive historical collection of [committee reports](http://www.gpo.gov/fdsys/browse/collection.action?collectionCode=CRPT) that can out of date by a year, but is the only source of historical work.

* The US Navy has an inspector general, with a two-page [reading room](http://www.secnav.navy.mil/ig/Pages/FOIA/ReadingRoom.aspx), I think with only reports that came out of FOIA.

* The US Marines inspector general has a [messy website](http://www.hqmc.marines.mil/igmc/UnitHome.aspx) that might have reports buried either inside, or on the sidebar.

* I can't find any reports for the inspectors general for the [US Army](http://www.daig.pentagon.mil/) or the [US Air Force](http://www.af.mil/InspectorGeneralComplaints.aspx), but maybe you'll have better luck than me.

Additionally, you could look over the IGs for whom we don't have any reliable report locations, and either verify that this is the case, or identify some reputable third party sources where we might find some. Those IGs are:

* [Architect of the Capitol](http://www.aoc.gov/aoc/oig.cfm)
* [Capitol Police](http://www.uscapitolpolice.gov/oig.php)
* [Central Intelligence Agency](https://www.cia.gov/offices-of-cia/inspector-general)
* [Defense Intelligence Agency](http://www.dia.mil/about/inspector-general/)
* [National Geospatial-Intelligence Agency](https://www1.nga.mil/About/Pages/InspectorGeneral.aspx)
* [National Reconnaissance Office](http://www.nro.gov/offices/oig/cd.html)
* [National Security Agency](http://www.nsa.gov/about/oig/index.shtml)
* [Intelligence Community](http://www.dni.gov/index.php/about/organization/office-of-the-intelligence-community-inspector-general-who-we-are) (ODNI)
* [Special Inspector General for Iraq Reconstruction](http://www.sigir.mil/)

We'd also love it if people could identify any room for improvement in existing scrapers, or felt moved to tackle any of the [open issues](https://github.com/unitedstates/inspectors-general/issues).

Thanks for inquiring, and for being interested in the project for your class! This was a useful thing to write down.

**Comment by jackiekazil** [comment]
@konklone this helpful! Thank you!
