### ISSUE TITLE
[doj] Website changes

### ISSUE THREAD

**Issue by divergentdave** [unitedstates/inspectors-general#228]
The Department of Justice OIG website has been moved to [its own subdomain](https://oig.justice.gov/), and migrated to HTTPS. The scraper will need some TLC, since the base URL has changed.

Unfortunately, the server only supports TLS_RSA_WITH_RC4_128_SHA, which is already deprecated. Newer versions of urllib3 (since 1.10.2) don't support RC4 by default. Options for a workaround are downgrading, [this](https://gist.github.com/paxswill/5ed7273059b34e90b184), and shazow/urllib3#617.

**Comment by konklone** [comment]
I've written the DOJ OIG to request they re-evaluate their ciphersuite choices. Thanks for raising this.

**Comment by divergentdave** [comment]
One month on, still only one ciphersuite. :( See also #229 for fixes.
