### ISSUE TITLE
LSC website has been redesigned

### ISSUE THREAD

**Issue by divergentdave** [unitedstates/inspectors-general#233]
The LSC OIG has a brand new website, much more modern-looking. The scraper will need a significant rewrite to adapt to this. Initial observations:

- The pages no longer include publish dates for the different reports, so we'll need to either hardcode all of them or just return i.e. November 1st of that year.
- There's an RSS feed, but it only has the five most recent reports, so it won't be of use.
- The financial statements/audits of the corporation no longer have a separate page, they are now on the audit report pages as well.
- Note to self: don't forget to scrape the "archives" pages.
- The "client trust fund" reports are included in the new "other reports archive" page

**Comment by konklone** [comment]
* And HTTPS too! :lock: :+1:
