### ISSUE TITLE
DOI OIG has moved to a new site

### ISSUE THREAD

**Issue by konklone** [unitedstates/inspectors-general#234]
At their own domain, and forcing HTTPS: https://www.doioig.gov

Going to require at least small changes to the scraper we have.

**Comment by divergentdave** [comment]
From https://www.doioig.gov/reports -- "Our report database is currently under construction. Full report search functionality will be available on August 10, 2015." :frowning: I'll take `interior` off the safe list for now.

**Comment by divergentdave** [comment]
Report search hasn't been rolled out yet, and there isn't an estimated completion date now.

**Comment by konklone** [comment]
Well. I guess there's 78 pages worth of search results for "the":

https://www.doioig.gov/search/node/the?page=78

This seems pretty ridiculous. I tweeted at them, but...I don't know. Since DOI's main site just moved this week, I guess I'll give them a little bit more time to update before emailing/calling.

**Comment by divergentdave** [comment]
That's Drupal's built-in search, the page at https://www.doioig.gov/reports says their reports database still isn't ready yet. (Two weeks behind the original schedule, no estimate posted now) It looks like they are creating objects in Drupal for each report, some of which are showing up in the default search page. Presumably they are working on adding the rest and creating a new view with better suited filtering and searching.

**Comment by divergentdave** [comment]
The report database is now online!
