### ISSUE TITLE
HTTPS upgrades

### ISSUE THREAD

**Issue by divergentdave** [unitedstates/inspectors-general#248]
There are a few OIG websites that have HTTPS available now, we should upgrade these scrapers accordingly. (starting with `inspector_url` in the reports)

- [x] Amtrak, https://www.amtrakoig.gov/
- [x] NARA, https://www.archives.gov/oig/
- [x] Commerce, https://www.oig.doc.gov/Pages/default.aspx
- [x] CPSC, https://www.cpsc.gov/en/About-CPSC/Inspector-General/
- [x] DHS: https://www.oig.dhs.gov/
- [x] FDIC: https://www.fdicig.gov/
- [x] Federal Reserve: https://oig.federalreserve.gov/
- [x] FTC: https://www.ftc.gov/about-ftc/office-inspector-general
- [x] GSA: https://www.gsaig.gov/
- [x] House: https://www.house.gov/content/learn/officers_and_organizations/inspector_general.php
- [x] HUD: https://www.hudoig.gov/
- [x] Interior: https://www.doioig.gov/ (see #234)
- [x] Labor: https://www.oig.dol.gov/
- [x] NASA: https://oig.nasa.gov/
- [x] SEC: https://www.sec.gov/oig
- [x] SIGAR: https://www.sigar.mil/
- [x] SIGTARP: https://www.sigtarp.gov/Pages/home.aspx
- [x] TIGTA: https://www.treasury.gov/tigta/

**Comment by konklone** [comment]
And I recall us already upgrading a few over the last several months.

CCing @csoghoian, who I think would be happy to see this.

**Comment by divergentdave** [comment]
These OIG websites became HTTPS-ready in the past few months

- https://www.cncsoig.gov/
- https://www.ed.gov/
- https://www.fca.gov/
- https://www.fcc.gov/

**Comment by divergentdave** [comment]
These OIG websites became HTTPS-ready in the past few months

- https://www.cncsoig.gov/
- https://www.fcc.gov/
